services:
  - type: static_site
    name: swiftmart-nhcx  # Your service name here
    env: node
    buildCommand: npm install && npm run build
    publishDirectory: build
    routes:
      - path: /*
        destination: /index.html
